#project 
#v1.1

  version: '2.2'
  service:
     build:
   volumes:
         dock:
  services:
         build:
          volumes:
                 - dock:/home/boxfuse/target/
             build: prod

             ports:
                   - "8080:8080"
