#project
#v3

version: "3.8"

services:
   work:
      build: work
      volumes:
       - data-volume:/usr/local/tomcat/webapps
   prod:
      build: prod
      volumes:
       - data-volume:/usr/tomcat
   ports:
    - "8080:8080"
volumes:
    data-volume:
