
#project
#v3

version: "3.8"

services:
   work:
      build: work
      volumes:
       - ./data:/usr/local/tomcat/webapps - здесь что не так
   prod:
      build: prod
      volumes:
       - ./data/usr/tomcat и здесь также
       ports:
      - "8080:8080"
