#v3.8
#docker-compose

version: '3.8'
services:
  work:
     build: ./dock/work
     volumes:
      - war_volume:/usr/local/tomcat/webapps
  prod:
     image: tomcat
     volumes:
      - war_volume:/usr/local/tomcat/webapps
     ports:
      - "8080:8080"
     restart: always
   volumes:
      war_volume:
# docker-compose up -d